apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wikipulse-worker-hpa
  labels:
    app: wikipulse-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wikipulse-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70